name: Ada (GNAT)

on:
  push:
    branches: [ trunk ]
  pull_request:
    branches: [ trunk ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up GNAT toolchain
      run: >
        sudo apt-get update &&
        sudo apt-get install adacontrol gnat

    - name: Build
      run: >
        make adactl &&
        cd gnat &&
          make &&
          make adactl
